/**
 * @file Continental Encoutners.Designer.cs
 * @author: Adair Torres
 * @brief: This file contains code automatically generated by the Visual Studio Designer. The InitializeComponent method should NOT be modified manually.
 * @last modified: 10/28/2022
**/

namespace Continental_Encounters
{
    partial class ContinentForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.MainMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.viewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ListFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.ZoneGroupBox = new System.Windows.Forms.GroupBox();
            this.NewZoneBox = new System.Windows.Forms.GroupBox();
            this.RemoveZoneBtn = new System.Windows.Forms.Button();
            this.ZoneInput = new System.Windows.Forms.TextBox();
            this.AddZoneBtn = new System.Windows.Forms.Button();
            this.ZoneListBox = new System.Windows.Forms.ListBox();
            this.EncountersGroupBox = new System.Windows.Forms.GroupBox();
            this.NewEncounterBox = new System.Windows.Forms.GroupBox();
            this.RemoveEncounterBtn = new System.Windows.Forms.Button();
            this.EncounterInput = new System.Windows.Forms.TextBox();
            this.AddEncounterBtn = new System.Windows.Forms.Button();
            this.EncounterListBox = new System.Windows.Forms.ListBox();
            this.RoamersGroupBox = new System.Windows.Forms.GroupBox();
            this.NewRoamerBox = new System.Windows.Forms.GroupBox();
            this.RemoveRoamerBtn = new System.Windows.Forms.Button();
            this.RoamerInput = new System.Windows.Forms.TextBox();
            this.AddRoamerBtn = new System.Windows.Forms.Button();
            this.RoamerListBox = new System.Windows.Forms.ListBox();
            this.EnvironmentsGroupBox = new System.Windows.Forms.GroupBox();
            this.NewEnvironmentBox = new System.Windows.Forms.GroupBox();
            this.RemoveEnvironmentBtn = new System.Windows.Forms.Button();
            this.EnvironmentInput = new System.Windows.Forms.TextBox();
            this.AddEnvironmentBtn = new System.Windows.Forms.Button();
            this.EnvironmentListBox = new System.Windows.Forms.ListBox();
            this.NeighborsGroupBox = new System.Windows.Forms.GroupBox();
            this.NewNeighborBox = new System.Windows.Forms.GroupBox();
            this.RemoveNeighborBtn = new System.Windows.Forms.Button();
            this.NeighborInput = new System.Windows.Forms.TextBox();
            this.AddNeighborBtn = new System.Windows.Forms.Button();
            this.NeighborListBox = new System.Windows.Forms.ListBox();
            this.GeneratorGroupBox = new System.Windows.Forms.GroupBox();
            this.GeneratorFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.GenerateBtn = new System.Windows.Forms.Button();
            this.OptionsFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.EncounterCheck = new System.Windows.Forms.CheckBox();
            this.RoamerCheck = new System.Windows.Forms.CheckBox();
            this.EnvironmentCheck = new System.Windows.Forms.CheckBox();
            this.AllRadio = new System.Windows.Forms.RadioButton();
            this.RandomRadio = new System.Windows.Forms.RadioButton();
            this.ResultFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.EnvironmentGenBox = new System.Windows.Forms.GroupBox();
            this.EnvironmentGenLabel = new System.Windows.Forms.Label();
            this.RoamerGenBox = new System.Windows.Forms.GroupBox();
            this.RoamerGenLabel = new System.Windows.Forms.Label();
            this.EncounterGenBox = new System.Windows.Forms.GroupBox();
            this.EncounterGenLabel = new System.Windows.Forms.Label();
            this.AddZoneTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveZoneTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddEncounterTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveEncounterTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddRoamerTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveRoamerTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddEnvironmentTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveEnvironmentTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddNeighborTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveNeighborTip = new System.Windows.Forms.ToolTip(this.components);
            this.ToolTabs = new System.Windows.Forms.TabControl();
            this.ContinentTab = new System.Windows.Forms.TabPage();
            this.SendPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.SendLabel = new System.Windows.Forms.Label();
            this.ContToEncButton = new System.Windows.Forms.Button();
            this.ContToTrackButton = new System.Windows.Forms.Button();
            this.ContToNotesButton = new System.Windows.Forms.Button();
            this.ContFilePanel = new System.Windows.Forms.FlowLayoutPanel();
            this.OpenContButton = new System.Windows.Forms.Button();
            this.SaveContButton = new System.Windows.Forms.Button();
            this.SaveContAsButton = new System.Windows.Forms.Button();
            this.CampaignTab = new System.Windows.Forms.TabPage();
            this.CombatTab = new System.Windows.Forms.TabPage();
            this.EncounterTab = new System.Windows.Forms.TabPage();
            this.CompendiumTab = new System.Windows.Forms.TabPage();
            this.CreationTab = new System.Windows.Forms.TabPage();
            this.MainMenuStrip.SuspendLayout();
            this.ListFlow.SuspendLayout();
            this.ZoneGroupBox.SuspendLayout();
            this.NewZoneBox.SuspendLayout();
            this.EncountersGroupBox.SuspendLayout();
            this.NewEncounterBox.SuspendLayout();
            this.RoamersGroupBox.SuspendLayout();
            this.NewRoamerBox.SuspendLayout();
            this.EnvironmentsGroupBox.SuspendLayout();
            this.NewEnvironmentBox.SuspendLayout();
            this.NeighborsGroupBox.SuspendLayout();
            this.NewNeighborBox.SuspendLayout();
            this.GeneratorGroupBox.SuspendLayout();
            this.GeneratorFlow.SuspendLayout();
            this.OptionsFlow.SuspendLayout();
            this.ResultFlow.SuspendLayout();
            this.EnvironmentGenBox.SuspendLayout();
            this.RoamerGenBox.SuspendLayout();
            this.EncounterGenBox.SuspendLayout();
            this.ToolTabs.SuspendLayout();
            this.ContinentTab.SuspendLayout();
            this.SendPanel.SuspendLayout();
            this.ContFilePanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // MainMenuStrip
            // 
            this.MainMenuStrip.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.MainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.editToolStripMenuItem,
            this.viewToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.MainMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.MainMenuStrip.Name = "MainMenuStrip";
            this.MainMenuStrip.Padding = new System.Windows.Forms.Padding(4, 2, 0, 2);
            this.MainMenuStrip.Size = new System.Drawing.Size(1329, 24);
            this.MainMenuStrip.TabIndex = 0;
            this.MainMenuStrip.Text = "BaseMenuStrip";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // editToolStripMenuItem
            // 
            this.editToolStripMenuItem.Name = "editToolStripMenuItem";
            this.editToolStripMenuItem.Size = new System.Drawing.Size(39, 20);
            this.editToolStripMenuItem.Text = "Edit";
            // 
            // viewToolStripMenuItem
            // 
            this.viewToolStripMenuItem.Name = "viewToolStripMenuItem";
            this.viewToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.viewToolStripMenuItem.Text = "View";
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "Help";
            // 
            // ListFlow
            // 
            this.ListFlow.Controls.Add(this.ZoneGroupBox);
            this.ListFlow.Controls.Add(this.EncountersGroupBox);
            this.ListFlow.Controls.Add(this.RoamersGroupBox);
            this.ListFlow.Controls.Add(this.EnvironmentsGroupBox);
            this.ListFlow.Controls.Add(this.NeighborsGroupBox);
            this.ListFlow.Location = new System.Drawing.Point(3, 39);
            this.ListFlow.Margin = new System.Windows.Forms.Padding(0);
            this.ListFlow.Name = "ListFlow";
            this.ListFlow.Size = new System.Drawing.Size(1061, 313);
            this.ListFlow.TabIndex = 1;
            // 
            // ZoneGroupBox
            // 
            this.ZoneGroupBox.Controls.Add(this.NewZoneBox);
            this.ZoneGroupBox.Controls.Add(this.ZoneListBox);
            this.ZoneGroupBox.Location = new System.Drawing.Point(3, 3);
            this.ZoneGroupBox.Name = "ZoneGroupBox";
            this.ZoneGroupBox.Size = new System.Drawing.Size(204, 306);
            this.ZoneGroupBox.TabIndex = 0;
            this.ZoneGroupBox.TabStop = false;
            this.ZoneGroupBox.Text = "Zones";
            // 
            // NewZoneBox
            // 
            this.NewZoneBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NewZoneBox.Controls.Add(this.RemoveZoneBtn);
            this.NewZoneBox.Controls.Add(this.ZoneInput);
            this.NewZoneBox.Controls.Add(this.AddZoneBtn);
            this.NewZoneBox.Location = new System.Drawing.Point(10, 19);
            this.NewZoneBox.Name = "NewZoneBox";
            this.NewZoneBox.Size = new System.Drawing.Size(182, 45);
            this.NewZoneBox.TabIndex = 2;
            this.NewZoneBox.TabStop = false;
            this.NewZoneBox.Text = "New Zone";
            // 
            // RemoveZoneBtn
            // 
            this.RemoveZoneBtn.ForeColor = System.Drawing.Color.Red;
            this.RemoveZoneBtn.Location = new System.Drawing.Point(153, 17);
            this.RemoveZoneBtn.Name = "RemoveZoneBtn";
            this.RemoveZoneBtn.Size = new System.Drawing.Size(23, 23);
            this.RemoveZoneBtn.TabIndex = 2;
            this.RemoveZoneBtn.Text = "X";
            this.RemoveZoneBtn.UseVisualStyleBackColor = true;
            // 
            // ZoneInput
            // 
            this.ZoneInput.Location = new System.Drawing.Point(6, 19);
            this.ZoneInput.Name = "ZoneInput";
            this.ZoneInput.Size = new System.Drawing.Size(121, 20);
            this.ZoneInput.TabIndex = 0;
            // 
            // AddZoneBtn
            // 
            this.AddZoneBtn.ForeColor = System.Drawing.Color.Green;
            this.AddZoneBtn.Location = new System.Drawing.Point(131, 17);
            this.AddZoneBtn.Name = "AddZoneBtn";
            this.AddZoneBtn.Size = new System.Drawing.Size(23, 23);
            this.AddZoneBtn.TabIndex = 1;
            this.AddZoneBtn.Text = "+";
            this.AddZoneBtn.UseVisualStyleBackColor = true;
            this.AddZoneBtn.Click += new System.EventHandler(this.AddZoneBtn_Click);
            // 
            // ZoneListBox
            // 
            this.ZoneListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ZoneListBox.FormattingEnabled = true;
            this.ZoneListBox.Location = new System.Drawing.Point(10, 70);
            this.ZoneListBox.Name = "ZoneListBox";
            this.ZoneListBox.Size = new System.Drawing.Size(182, 225);
            this.ZoneListBox.TabIndex = 1;
            this.ZoneListBox.SelectedIndexChanged += new System.EventHandler(this.ZoneListBox_SelectedIndexChanged);
            // 
            // EncountersGroupBox
            // 
            this.EncountersGroupBox.Controls.Add(this.NewEncounterBox);
            this.EncountersGroupBox.Controls.Add(this.EncounterListBox);
            this.EncountersGroupBox.Location = new System.Drawing.Point(213, 3);
            this.EncountersGroupBox.Name = "EncountersGroupBox";
            this.EncountersGroupBox.Size = new System.Drawing.Size(204, 306);
            this.EncountersGroupBox.TabIndex = 1;
            this.EncountersGroupBox.TabStop = false;
            this.EncountersGroupBox.Text = "Encounters";
            // 
            // NewEncounterBox
            // 
            this.NewEncounterBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NewEncounterBox.Controls.Add(this.RemoveEncounterBtn);
            this.NewEncounterBox.Controls.Add(this.EncounterInput);
            this.NewEncounterBox.Controls.Add(this.AddEncounterBtn);
            this.NewEncounterBox.Location = new System.Drawing.Point(10, 19);
            this.NewEncounterBox.Name = "NewEncounterBox";
            this.NewEncounterBox.Size = new System.Drawing.Size(182, 45);
            this.NewEncounterBox.TabIndex = 2;
            this.NewEncounterBox.TabStop = false;
            this.NewEncounterBox.Text = "New Encounter";
            // 
            // RemoveEncounterBtn
            // 
            this.RemoveEncounterBtn.ForeColor = System.Drawing.Color.Red;
            this.RemoveEncounterBtn.Location = new System.Drawing.Point(153, 17);
            this.RemoveEncounterBtn.Name = "RemoveEncounterBtn";
            this.RemoveEncounterBtn.Size = new System.Drawing.Size(23, 23);
            this.RemoveEncounterBtn.TabIndex = 2;
            this.RemoveEncounterBtn.Text = "X";
            this.RemoveEncounterBtn.UseVisualStyleBackColor = true;
            // 
            // EncounterInput
            // 
            this.EncounterInput.Location = new System.Drawing.Point(6, 19);
            this.EncounterInput.Name = "EncounterInput";
            this.EncounterInput.Size = new System.Drawing.Size(121, 20);
            this.EncounterInput.TabIndex = 0;
            // 
            // AddEncounterBtn
            // 
            this.AddEncounterBtn.ForeColor = System.Drawing.Color.Green;
            this.AddEncounterBtn.Location = new System.Drawing.Point(131, 17);
            this.AddEncounterBtn.Name = "AddEncounterBtn";
            this.AddEncounterBtn.Size = new System.Drawing.Size(23, 23);
            this.AddEncounterBtn.TabIndex = 1;
            this.AddEncounterBtn.Text = "+";
            this.AddEncounterBtn.UseVisualStyleBackColor = true;
            // 
            // EncounterListBox
            // 
            this.EncounterListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.EncounterListBox.FormattingEnabled = true;
            this.EncounterListBox.Location = new System.Drawing.Point(10, 70);
            this.EncounterListBox.Name = "EncounterListBox";
            this.EncounterListBox.Size = new System.Drawing.Size(182, 225);
            this.EncounterListBox.TabIndex = 1;
            // 
            // RoamersGroupBox
            // 
            this.RoamersGroupBox.Controls.Add(this.NewRoamerBox);
            this.RoamersGroupBox.Controls.Add(this.RoamerListBox);
            this.RoamersGroupBox.Location = new System.Drawing.Point(423, 3);
            this.RoamersGroupBox.Name = "RoamersGroupBox";
            this.RoamersGroupBox.Size = new System.Drawing.Size(204, 306);
            this.RoamersGroupBox.TabIndex = 2;
            this.RoamersGroupBox.TabStop = false;
            this.RoamersGroupBox.Text = "Roamers";
            // 
            // NewRoamerBox
            // 
            this.NewRoamerBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NewRoamerBox.Controls.Add(this.RemoveRoamerBtn);
            this.NewRoamerBox.Controls.Add(this.RoamerInput);
            this.NewRoamerBox.Controls.Add(this.AddRoamerBtn);
            this.NewRoamerBox.Location = new System.Drawing.Point(6, 19);
            this.NewRoamerBox.Name = "NewRoamerBox";
            this.NewRoamerBox.Size = new System.Drawing.Size(182, 45);
            this.NewRoamerBox.TabIndex = 2;
            this.NewRoamerBox.TabStop = false;
            this.NewRoamerBox.Text = "New Roamer";
            // 
            // RemoveRoamerBtn
            // 
            this.RemoveRoamerBtn.ForeColor = System.Drawing.Color.Red;
            this.RemoveRoamerBtn.Location = new System.Drawing.Point(153, 17);
            this.RemoveRoamerBtn.Name = "RemoveRoamerBtn";
            this.RemoveRoamerBtn.Size = new System.Drawing.Size(23, 23);
            this.RemoveRoamerBtn.TabIndex = 2;
            this.RemoveRoamerBtn.Text = "X";
            this.RemoveRoamerBtn.UseVisualStyleBackColor = true;
            // 
            // RoamerInput
            // 
            this.RoamerInput.Location = new System.Drawing.Point(6, 19);
            this.RoamerInput.Name = "RoamerInput";
            this.RoamerInput.Size = new System.Drawing.Size(121, 20);
            this.RoamerInput.TabIndex = 0;
            // 
            // AddRoamerBtn
            // 
            this.AddRoamerBtn.ForeColor = System.Drawing.Color.Green;
            this.AddRoamerBtn.Location = new System.Drawing.Point(131, 17);
            this.AddRoamerBtn.Name = "AddRoamerBtn";
            this.AddRoamerBtn.Size = new System.Drawing.Size(23, 23);
            this.AddRoamerBtn.TabIndex = 1;
            this.AddRoamerBtn.Text = "+";
            this.AddRoamerBtn.UseVisualStyleBackColor = true;
            // 
            // RoamerListBox
            // 
            this.RoamerListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.RoamerListBox.FormattingEnabled = true;
            this.RoamerListBox.Location = new System.Drawing.Point(10, 70);
            this.RoamerListBox.Name = "RoamerListBox";
            this.RoamerListBox.Size = new System.Drawing.Size(182, 225);
            this.RoamerListBox.TabIndex = 1;
            // 
            // EnvironmentsGroupBox
            // 
            this.EnvironmentsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.EnvironmentsGroupBox.Controls.Add(this.NewEnvironmentBox);
            this.EnvironmentsGroupBox.Controls.Add(this.EnvironmentListBox);
            this.EnvironmentsGroupBox.Location = new System.Drawing.Point(633, 3);
            this.EnvironmentsGroupBox.Name = "EnvironmentsGroupBox";
            this.EnvironmentsGroupBox.Size = new System.Drawing.Size(204, 306);
            this.EnvironmentsGroupBox.TabIndex = 3;
            this.EnvironmentsGroupBox.TabStop = false;
            this.EnvironmentsGroupBox.Text = "Environments";
            // 
            // NewEnvironmentBox
            // 
            this.NewEnvironmentBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NewEnvironmentBox.Controls.Add(this.RemoveEnvironmentBtn);
            this.NewEnvironmentBox.Controls.Add(this.EnvironmentInput);
            this.NewEnvironmentBox.Controls.Add(this.AddEnvironmentBtn);
            this.NewEnvironmentBox.Location = new System.Drawing.Point(10, 19);
            this.NewEnvironmentBox.Name = "NewEnvironmentBox";
            this.NewEnvironmentBox.Size = new System.Drawing.Size(182, 45);
            this.NewEnvironmentBox.TabIndex = 2;
            this.NewEnvironmentBox.TabStop = false;
            this.NewEnvironmentBox.Text = "New Environment";
            // 
            // RemoveEnvironmentBtn
            // 
            this.RemoveEnvironmentBtn.ForeColor = System.Drawing.Color.Red;
            this.RemoveEnvironmentBtn.Location = new System.Drawing.Point(153, 17);
            this.RemoveEnvironmentBtn.Name = "RemoveEnvironmentBtn";
            this.RemoveEnvironmentBtn.Size = new System.Drawing.Size(23, 23);
            this.RemoveEnvironmentBtn.TabIndex = 2;
            this.RemoveEnvironmentBtn.Text = "X";
            this.RemoveEnvironmentBtn.UseVisualStyleBackColor = true;
            // 
            // EnvironmentInput
            // 
            this.EnvironmentInput.Location = new System.Drawing.Point(6, 19);
            this.EnvironmentInput.Name = "EnvironmentInput";
            this.EnvironmentInput.Size = new System.Drawing.Size(121, 20);
            this.EnvironmentInput.TabIndex = 0;
            // 
            // AddEnvironmentBtn
            // 
            this.AddEnvironmentBtn.ForeColor = System.Drawing.Color.Green;
            this.AddEnvironmentBtn.Location = new System.Drawing.Point(131, 17);
            this.AddEnvironmentBtn.Name = "AddEnvironmentBtn";
            this.AddEnvironmentBtn.Size = new System.Drawing.Size(23, 23);
            this.AddEnvironmentBtn.TabIndex = 1;
            this.AddEnvironmentBtn.Text = "+";
            this.AddEnvironmentBtn.UseVisualStyleBackColor = true;
            // 
            // EnvironmentListBox
            // 
            this.EnvironmentListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.EnvironmentListBox.FormattingEnabled = true;
            this.EnvironmentListBox.Location = new System.Drawing.Point(10, 70);
            this.EnvironmentListBox.Name = "EnvironmentListBox";
            this.EnvironmentListBox.Size = new System.Drawing.Size(182, 225);
            this.EnvironmentListBox.TabIndex = 1;
            // 
            // NeighborsGroupBox
            // 
            this.NeighborsGroupBox.Controls.Add(this.NewNeighborBox);
            this.NeighborsGroupBox.Controls.Add(this.NeighborListBox);
            this.NeighborsGroupBox.Location = new System.Drawing.Point(843, 3);
            this.NeighborsGroupBox.Name = "NeighborsGroupBox";
            this.NeighborsGroupBox.Size = new System.Drawing.Size(204, 306);
            this.NeighborsGroupBox.TabIndex = 4;
            this.NeighborsGroupBox.TabStop = false;
            this.NeighborsGroupBox.Text = "Neighbor Zones";
            // 
            // NewNeighborBox
            // 
            this.NewNeighborBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NewNeighborBox.Controls.Add(this.RemoveNeighborBtn);
            this.NewNeighborBox.Controls.Add(this.NeighborInput);
            this.NewNeighborBox.Controls.Add(this.AddNeighborBtn);
            this.NewNeighborBox.Location = new System.Drawing.Point(10, 19);
            this.NewNeighborBox.Name = "NewNeighborBox";
            this.NewNeighborBox.Size = new System.Drawing.Size(182, 45);
            this.NewNeighborBox.TabIndex = 2;
            this.NewNeighborBox.TabStop = false;
            this.NewNeighborBox.Text = "New Neighbor";
            // 
            // RemoveNeighborBtn
            // 
            this.RemoveNeighborBtn.ForeColor = System.Drawing.Color.Red;
            this.RemoveNeighborBtn.Location = new System.Drawing.Point(153, 17);
            this.RemoveNeighborBtn.Name = "RemoveNeighborBtn";
            this.RemoveNeighborBtn.Size = new System.Drawing.Size(23, 23);
            this.RemoveNeighborBtn.TabIndex = 2;
            this.RemoveNeighborBtn.Text = "X";
            this.RemoveNeighborBtn.UseVisualStyleBackColor = true;
            // 
            // NeighborInput
            // 
            this.NeighborInput.Location = new System.Drawing.Point(6, 19);
            this.NeighborInput.Name = "NeighborInput";
            this.NeighborInput.Size = new System.Drawing.Size(121, 20);
            this.NeighborInput.TabIndex = 0;
            // 
            // AddNeighborBtn
            // 
            this.AddNeighborBtn.ForeColor = System.Drawing.Color.Green;
            this.AddNeighborBtn.Location = new System.Drawing.Point(131, 17);
            this.AddNeighborBtn.Name = "AddNeighborBtn";
            this.AddNeighborBtn.Size = new System.Drawing.Size(23, 23);
            this.AddNeighborBtn.TabIndex = 1;
            this.AddNeighborBtn.Text = "+";
            this.AddNeighborBtn.UseVisualStyleBackColor = true;
            // 
            // NeighborListBox
            // 
            this.NeighborListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NeighborListBox.FormattingEnabled = true;
            this.NeighborListBox.Location = new System.Drawing.Point(10, 70);
            this.NeighborListBox.Name = "NeighborListBox";
            this.NeighborListBox.Size = new System.Drawing.Size(182, 225);
            this.NeighborListBox.TabIndex = 1;
            // 
            // GeneratorGroupBox
            // 
            this.GeneratorGroupBox.Controls.Add(this.GeneratorFlow);
            this.GeneratorGroupBox.Location = new System.Drawing.Point(6, 352);
            this.GeneratorGroupBox.Margin = new System.Windows.Forms.Padding(0);
            this.GeneratorGroupBox.Name = "GeneratorGroupBox";
            this.GeneratorGroupBox.Padding = new System.Windows.Forms.Padding(0);
            this.GeneratorGroupBox.Size = new System.Drawing.Size(1044, 203);
            this.GeneratorGroupBox.TabIndex = 2;
            this.GeneratorGroupBox.TabStop = false;
            this.GeneratorGroupBox.Text = "Generator";
            // 
            // GeneratorFlow
            // 
            this.GeneratorFlow.Controls.Add(this.GenerateBtn);
            this.GeneratorFlow.Controls.Add(this.OptionsFlow);
            this.GeneratorFlow.Controls.Add(this.ResultFlow);
            this.GeneratorFlow.Location = new System.Drawing.Point(5, 13);
            this.GeneratorFlow.Margin = new System.Windows.Forms.Padding(2);
            this.GeneratorFlow.Name = "GeneratorFlow";
            this.GeneratorFlow.Size = new System.Drawing.Size(1035, 178);
            this.GeneratorFlow.TabIndex = 0;
            // 
            // GenerateBtn
            // 
            this.GenerateBtn.Location = new System.Drawing.Point(3, 3);
            this.GenerateBtn.Name = "GenerateBtn";
            this.GenerateBtn.Size = new System.Drawing.Size(180, 166);
            this.GenerateBtn.TabIndex = 0;
            this.GenerateBtn.Text = "Generate Encounter!";
            this.GenerateBtn.UseVisualStyleBackColor = true;
            // 
            // OptionsFlow
            // 
            this.OptionsFlow.Controls.Add(this.EncounterCheck);
            this.OptionsFlow.Controls.Add(this.RoamerCheck);
            this.OptionsFlow.Controls.Add(this.EnvironmentCheck);
            this.OptionsFlow.Controls.Add(this.AllRadio);
            this.OptionsFlow.Controls.Add(this.RandomRadio);
            this.OptionsFlow.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.OptionsFlow.Location = new System.Drawing.Point(188, 2);
            this.OptionsFlow.Margin = new System.Windows.Forms.Padding(2);
            this.OptionsFlow.Name = "OptionsFlow";
            this.OptionsFlow.Size = new System.Drawing.Size(132, 135);
            this.OptionsFlow.TabIndex = 1;
            // 
            // EncounterCheck
            // 
            this.EncounterCheck.AutoSize = true;
            this.EncounterCheck.Location = new System.Drawing.Point(3, 3);
            this.EncounterCheck.Name = "EncounterCheck";
            this.EncounterCheck.Size = new System.Drawing.Size(113, 17);
            this.EncounterCheck.TabIndex = 0;
            this.EncounterCheck.Text = "Include Encounter";
            this.EncounterCheck.UseVisualStyleBackColor = true;
            // 
            // RoamerCheck
            // 
            this.RoamerCheck.AutoSize = true;
            this.RoamerCheck.Location = new System.Drawing.Point(3, 26);
            this.RoamerCheck.Name = "RoamerCheck";
            this.RoamerCheck.Size = new System.Drawing.Size(101, 17);
            this.RoamerCheck.TabIndex = 1;
            this.RoamerCheck.Text = "Include Roamer";
            this.RoamerCheck.UseVisualStyleBackColor = true;
            // 
            // EnvironmentCheck
            // 
            this.EnvironmentCheck.AutoSize = true;
            this.EnvironmentCheck.Location = new System.Drawing.Point(3, 49);
            this.EnvironmentCheck.Name = "EnvironmentCheck";
            this.EnvironmentCheck.Size = new System.Drawing.Size(123, 17);
            this.EnvironmentCheck.TabIndex = 2;
            this.EnvironmentCheck.Text = "Include Environment";
            this.EnvironmentCheck.UseVisualStyleBackColor = true;
            // 
            // AllRadio
            // 
            this.AllRadio.AutoSize = true;
            this.AllRadio.Location = new System.Drawing.Point(3, 72);
            this.AllRadio.Name = "AllRadio";
            this.AllRadio.Size = new System.Drawing.Size(74, 17);
            this.AllRadio.TabIndex = 4;
            this.AllRadio.TabStop = true;
            this.AllRadio.Text = "Include All";
            this.AllRadio.UseVisualStyleBackColor = true;
            // 
            // RandomRadio
            // 
            this.RandomRadio.AutoSize = true;
            this.RandomRadio.Location = new System.Drawing.Point(3, 95);
            this.RandomRadio.Name = "RandomRadio";
            this.RandomRadio.Size = new System.Drawing.Size(65, 17);
            this.RandomRadio.TabIndex = 5;
            this.RandomRadio.TabStop = true;
            this.RandomRadio.Text = "Random";
            this.RandomRadio.UseVisualStyleBackColor = true;
            // 
            // ResultFlow
            // 
            this.ResultFlow.Controls.Add(this.EnvironmentGenBox);
            this.ResultFlow.Controls.Add(this.RoamerGenBox);
            this.ResultFlow.Controls.Add(this.EncounterGenBox);
            this.ResultFlow.Location = new System.Drawing.Point(324, 2);
            this.ResultFlow.Margin = new System.Windows.Forms.Padding(2);
            this.ResultFlow.Name = "ResultFlow";
            this.ResultFlow.Size = new System.Drawing.Size(703, 167);
            this.ResultFlow.TabIndex = 2;
            // 
            // EnvironmentGenBox
            // 
            this.EnvironmentGenBox.Controls.Add(this.EnvironmentGenLabel);
            this.EnvironmentGenBox.Location = new System.Drawing.Point(3, 3);
            this.EnvironmentGenBox.Name = "EnvironmentGenBox";
            this.EnvironmentGenBox.Size = new System.Drawing.Size(225, 163);
            this.EnvironmentGenBox.TabIndex = 4;
            this.EnvironmentGenBox.TabStop = false;
            this.EnvironmentGenBox.Text = "Environment";
            // 
            // EnvironmentGenLabel
            // 
            this.EnvironmentGenLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.EnvironmentGenLabel.Location = new System.Drawing.Point(6, 20);
            this.EnvironmentGenLabel.Margin = new System.Windows.Forms.Padding(3);
            this.EnvironmentGenLabel.Name = "EnvironmentGenLabel";
            this.EnvironmentGenLabel.Size = new System.Drawing.Size(212, 137);
            this.EnvironmentGenLabel.TabIndex = 1;
            this.EnvironmentGenLabel.Text = "The generated environment will appear here!";
            // 
            // RoamerGenBox
            // 
            this.RoamerGenBox.Controls.Add(this.RoamerGenLabel);
            this.RoamerGenBox.Location = new System.Drawing.Point(234, 3);
            this.RoamerGenBox.Name = "RoamerGenBox";
            this.RoamerGenBox.Size = new System.Drawing.Size(225, 163);
            this.RoamerGenBox.TabIndex = 3;
            this.RoamerGenBox.TabStop = false;
            this.RoamerGenBox.Text = "Roamer";
            // 
            // RoamerGenLabel
            // 
            this.RoamerGenLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.RoamerGenLabel.Location = new System.Drawing.Point(6, 19);
            this.RoamerGenLabel.Margin = new System.Windows.Forms.Padding(3);
            this.RoamerGenLabel.Name = "RoamerGenLabel";
            this.RoamerGenLabel.Size = new System.Drawing.Size(212, 137);
            this.RoamerGenLabel.TabIndex = 1;
            this.RoamerGenLabel.Text = "The generated roamer will appear here!";
            // 
            // EncounterGenBox
            // 
            this.EncounterGenBox.Controls.Add(this.EncounterGenLabel);
            this.EncounterGenBox.Location = new System.Drawing.Point(465, 3);
            this.EncounterGenBox.Name = "EncounterGenBox";
            this.EncounterGenBox.Size = new System.Drawing.Size(225, 163);
            this.EncounterGenBox.TabIndex = 2;
            this.EncounterGenBox.TabStop = false;
            this.EncounterGenBox.Text = "Encounter";
            // 
            // EncounterGenLabel
            // 
            this.EncounterGenLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.EncounterGenLabel.Location = new System.Drawing.Point(7, 20);
            this.EncounterGenLabel.Margin = new System.Windows.Forms.Padding(3);
            this.EncounterGenLabel.Name = "EncounterGenLabel";
            this.EncounterGenLabel.Size = new System.Drawing.Size(212, 137);
            this.EncounterGenLabel.TabIndex = 0;
            this.EncounterGenLabel.Text = "The generated encounter will appear here!";
            // 
            // ToolTabs
            // 
            this.ToolTabs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ToolTabs.Appearance = System.Windows.Forms.TabAppearance.Buttons;
            this.ToolTabs.Controls.Add(this.ContinentTab);
            this.ToolTabs.Controls.Add(this.CampaignTab);
            this.ToolTabs.Controls.Add(this.CombatTab);
            this.ToolTabs.Controls.Add(this.EncounterTab);
            this.ToolTabs.Controls.Add(this.CompendiumTab);
            this.ToolTabs.Controls.Add(this.CreationTab);
            this.ToolTabs.Location = new System.Drawing.Point(12, 27);
            this.ToolTabs.Name = "ToolTabs";
            this.ToolTabs.SelectedIndex = 0;
            this.ToolTabs.Size = new System.Drawing.Size(1305, 608);
            this.ToolTabs.TabIndex = 1;
            // 
            // ContinentTab
            // 
            this.ContinentTab.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.ContinentTab.Controls.Add(this.SendPanel);
            this.ContinentTab.Controls.Add(this.ContFilePanel);
            this.ContinentTab.Controls.Add(this.GeneratorGroupBox);
            this.ContinentTab.Controls.Add(this.ListFlow);
            this.ContinentTab.Location = new System.Drawing.Point(4, 25);
            this.ContinentTab.Name = "ContinentTab";
            this.ContinentTab.Padding = new System.Windows.Forms.Padding(3);
            this.ContinentTab.Size = new System.Drawing.Size(1297, 579);
            this.ContinentTab.TabIndex = 0;
            this.ContinentTab.Text = "Continental Encounters";
            this.ContinentTab.UseVisualStyleBackColor = true;
            // 
            // SendPanel
            // 
            this.SendPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.SendPanel.Controls.Add(this.SendLabel);
            this.SendPanel.Controls.Add(this.ContToEncButton);
            this.SendPanel.Controls.Add(this.ContToTrackButton);
            this.SendPanel.Controls.Add(this.ContToNotesButton);
            this.SendPanel.Location = new System.Drawing.Point(794, 6);
            this.SendPanel.Name = "SendPanel";
            this.SendPanel.Size = new System.Drawing.Size(495, 30);
            this.SendPanel.TabIndex = 4;
            // 
            // SendLabel
            // 
            this.SendLabel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.SendLabel.AutoSize = true;
            this.SendLabel.Location = new System.Drawing.Point(3, 9);
            this.SendLabel.Name = "SendLabel";
            this.SendLabel.Size = new System.Drawing.Size(156, 13);
            this.SendLabel.TabIndex = 0;
            this.SendLabel.Text = "Send Generated Encounter To:";
            // 
            // ContToEncButton
            // 
            this.ContToEncButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ContToEncButton.Location = new System.Drawing.Point(165, 3);
            this.ContToEncButton.Name = "ContToEncButton";
            this.ContToEncButton.Size = new System.Drawing.Size(105, 25);
            this.ContToEncButton.TabIndex = 1;
            this.ContToEncButton.Text = "Encounter Planner";
            this.ContToEncButton.UseVisualStyleBackColor = true;
            // 
            // ContToTrackButton
            // 
            this.ContToTrackButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ContToTrackButton.Location = new System.Drawing.Point(276, 3);
            this.ContToTrackButton.Name = "ContToTrackButton";
            this.ContToTrackButton.Size = new System.Drawing.Size(105, 25);
            this.ContToTrackButton.TabIndex = 2;
            this.ContToTrackButton.Text = "Combat Tracker";
            this.ContToTrackButton.UseVisualStyleBackColor = true;
            // 
            // ContToNotesButton
            // 
            this.ContToNotesButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ContToNotesButton.Location = new System.Drawing.Point(387, 3);
            this.ContToNotesButton.Name = "ContToNotesButton";
            this.ContToNotesButton.Size = new System.Drawing.Size(105, 25);
            this.ContToNotesButton.TabIndex = 3;
            this.ContToNotesButton.Text = "Campaign Notes";
            this.ContToNotesButton.UseVisualStyleBackColor = true;
            // 
            // ContFilePanel
            // 
            this.ContFilePanel.Controls.Add(this.OpenContButton);
            this.ContFilePanel.Controls.Add(this.SaveContButton);
            this.ContFilePanel.Controls.Add(this.SaveContAsButton);
            this.ContFilePanel.Location = new System.Drawing.Point(3, 6);
            this.ContFilePanel.Name = "ContFilePanel";
            this.ContFilePanel.Size = new System.Drawing.Size(367, 30);
            this.ContFilePanel.TabIndex = 3;
            // 
            // OpenContButton
            // 
            this.OpenContButton.Location = new System.Drawing.Point(3, 3);
            this.OpenContButton.Name = "OpenContButton";
            this.OpenContButton.Size = new System.Drawing.Size(116, 23);
            this.OpenContButton.TabIndex = 0;
            this.OpenContButton.Text = "Open Continent";
            this.OpenContButton.UseVisualStyleBackColor = true;
            // 
            // SaveContButton
            // 
            this.SaveContButton.Location = new System.Drawing.Point(125, 3);
            this.SaveContButton.Name = "SaveContButton";
            this.SaveContButton.Size = new System.Drawing.Size(116, 23);
            this.SaveContButton.TabIndex = 1;
            this.SaveContButton.Text = "Save Continent";
            this.SaveContButton.UseVisualStyleBackColor = true;
            // 
            // SaveContAsButton
            // 
            this.SaveContAsButton.Location = new System.Drawing.Point(247, 3);
            this.SaveContAsButton.Name = "SaveContAsButton";
            this.SaveContAsButton.Size = new System.Drawing.Size(116, 23);
            this.SaveContAsButton.TabIndex = 2;
            this.SaveContAsButton.Text = "Save Continent As...";
            this.SaveContAsButton.UseVisualStyleBackColor = true;
            // 
            // CampaignTab
            // 
            this.CampaignTab.Location = new System.Drawing.Point(4, 25);
            this.CampaignTab.Name = "CampaignTab";
            this.CampaignTab.Padding = new System.Windows.Forms.Padding(3);
            this.CampaignTab.Size = new System.Drawing.Size(1297, 579);
            this.CampaignTab.TabIndex = 1;
            this.CampaignTab.Text = "Campaign Notes";
            this.CampaignTab.UseVisualStyleBackColor = true;
            // 
            // CombatTab
            // 
            this.CombatTab.Location = new System.Drawing.Point(4, 25);
            this.CombatTab.Name = "CombatTab";
            this.CombatTab.Padding = new System.Windows.Forms.Padding(3);
            this.CombatTab.Size = new System.Drawing.Size(1297, 579);
            this.CombatTab.TabIndex = 3;
            this.CombatTab.Text = "Combat Tracker";
            this.CombatTab.UseVisualStyleBackColor = true;
            // 
            // EncounterTab
            // 
            this.EncounterTab.Location = new System.Drawing.Point(4, 25);
            this.EncounterTab.Name = "EncounterTab";
            this.EncounterTab.Padding = new System.Windows.Forms.Padding(3);
            this.EncounterTab.Size = new System.Drawing.Size(1297, 579);
            this.EncounterTab.TabIndex = 5;
            this.EncounterTab.Text = "Encounter Planner";
            this.EncounterTab.UseVisualStyleBackColor = true;
            // 
            // CompendiumTab
            // 
            this.CompendiumTab.Location = new System.Drawing.Point(4, 25);
            this.CompendiumTab.Name = "CompendiumTab";
            this.CompendiumTab.Padding = new System.Windows.Forms.Padding(3);
            this.CompendiumTab.Size = new System.Drawing.Size(1297, 579);
            this.CompendiumTab.TabIndex = 4;
            this.CompendiumTab.Text = "Compendium";
            this.CompendiumTab.UseVisualStyleBackColor = true;
            // 
            // CreationTab
            // 
            this.CreationTab.Location = new System.Drawing.Point(4, 25);
            this.CreationTab.Name = "CreationTab";
            this.CreationTab.Padding = new System.Windows.Forms.Padding(3);
            this.CreationTab.Size = new System.Drawing.Size(1297, 579);
            this.CreationTab.TabIndex = 2;
            this.CreationTab.Text = "Creation Lab";
            this.CreationTab.UseVisualStyleBackColor = true;
            // 
            // ContinentForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1329, 647);
            this.Controls.Add(this.ToolTabs);
            this.Controls.Add(this.MainMenuStrip);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "ContinentForm";
            this.Text = "Continental Encounters";
            this.MainMenuStrip.ResumeLayout(false);
            this.MainMenuStrip.PerformLayout();
            this.ListFlow.ResumeLayout(false);
            this.ZoneGroupBox.ResumeLayout(false);
            this.NewZoneBox.ResumeLayout(false);
            this.NewZoneBox.PerformLayout();
            this.EncountersGroupBox.ResumeLayout(false);
            this.NewEncounterBox.ResumeLayout(false);
            this.NewEncounterBox.PerformLayout();
            this.RoamersGroupBox.ResumeLayout(false);
            this.NewRoamerBox.ResumeLayout(false);
            this.NewRoamerBox.PerformLayout();
            this.EnvironmentsGroupBox.ResumeLayout(false);
            this.NewEnvironmentBox.ResumeLayout(false);
            this.NewEnvironmentBox.PerformLayout();
            this.NeighborsGroupBox.ResumeLayout(false);
            this.NewNeighborBox.ResumeLayout(false);
            this.NewNeighborBox.PerformLayout();
            this.GeneratorGroupBox.ResumeLayout(false);
            this.GeneratorFlow.ResumeLayout(false);
            this.OptionsFlow.ResumeLayout(false);
            this.OptionsFlow.PerformLayout();
            this.ResultFlow.ResumeLayout(false);
            this.EnvironmentGenBox.ResumeLayout(false);
            this.RoamerGenBox.ResumeLayout(false);
            this.EncounterGenBox.ResumeLayout(false);
            this.ToolTabs.ResumeLayout(false);
            this.ContinentTab.ResumeLayout(false);
            this.SendPanel.ResumeLayout(false);
            this.SendPanel.PerformLayout();
            this.ContFilePanel.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        // Menubar
        private System.Windows.Forms.MenuStrip MainMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem viewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;

            // Lists Container
        private System.Windows.Forms.FlowLayoutPanel ListFlow;

            // Zone Group
        private System.Windows.Forms.GroupBox ZoneGroupBox;
                // Zone Input
        private System.Windows.Forms.GroupBox NewZoneBox;
        private System.Windows.Forms.TextBox ZoneInput;
        private System.Windows.Forms.Button AddZoneBtn;
        private System.Windows.Forms.ToolTip AddZoneTip;
        private System.Windows.Forms.Button RemoveZoneBtn;
        private System.Windows.Forms.ToolTip RemoveZoneTip;
                // Zone List
        private System.Windows.Forms.ListBox ZoneListBox;

            // Encounter Group
        private System.Windows.Forms.GroupBox EncountersGroupBox;
                // Encounter Input
        private System.Windows.Forms.GroupBox NewEncounterBox;
        private System.Windows.Forms.TextBox EncounterInput;
        private System.Windows.Forms.Button AddEncounterBtn;
        private System.Windows.Forms.ToolTip AddEncounterTip;
        private System.Windows.Forms.Button RemoveEncounterBtn;
        private System.Windows.Forms.ToolTip RemoveEncounterTip;
                // Encounter List
        private System.Windows.Forms.ListBox EncounterListBox;

            // Roamer Group
        private System.Windows.Forms.GroupBox RoamersGroupBox;
                // Roamer Input
        private System.Windows.Forms.GroupBox NewRoamerBox;
        private System.Windows.Forms.TextBox RoamerInput;
        private System.Windows.Forms.Button AddRoamerBtn;
        private System.Windows.Forms.ToolTip AddRoamerTip;
        private System.Windows.Forms.Button RemoveRoamerBtn;
        private System.Windows.Forms.ToolTip RemoveRoamerTip;
                // Roamer List
        private System.Windows.Forms.ListBox RoamerListBox;

            // Environment Group
        private System.Windows.Forms.GroupBox EnvironmentsGroupBox;
                // Environment Input
        private System.Windows.Forms.GroupBox NewEnvironmentBox;
        private System.Windows.Forms.TextBox EnvironmentInput;
        private System.Windows.Forms.Button AddEnvironmentBtn;
        private System.Windows.Forms.ToolTip AddEnvironmentTip;
        private System.Windows.Forms.Button RemoveEnvironmentBtn;
        private System.Windows.Forms.ToolTip RemoveEnvironmentTip;
                // Environment List
        private System.Windows.Forms.ListBox EnvironmentListBox;

            // Neighbor Group
        private System.Windows.Forms.GroupBox NeighborsGroupBox;
                // Neighbor Input
        private System.Windows.Forms.GroupBox NewNeighborBox;
        private System.Windows.Forms.TextBox NeighborInput;
        private System.Windows.Forms.Button AddNeighborBtn;
        private System.Windows.Forms.ToolTip AddNeighborTip;
        private System.Windows.Forms.Button RemoveNeighborBtn;
        private System.Windows.Forms.ToolTip RemoveNeighborTip;
                // Neighbor List
        private System.Windows.Forms.ListBox NeighborListBox;

        // Generator Container
        private System.Windows.Forms.GroupBox GeneratorGroupBox;
        private System.Windows.Forms.FlowLayoutPanel GeneratorFlow;
            // Generate Button
        private System.Windows.Forms.Button GenerateBtn;
            // Generator Options
        private System.Windows.Forms.FlowLayoutPanel OptionsFlow;
        private System.Windows.Forms.CheckBox EncounterCheck;
        private System.Windows.Forms.CheckBox RoamerCheck;
        private System.Windows.Forms.CheckBox EnvironmentCheck;
        private System.Windows.Forms.RadioButton AllRadio;
        private System.Windows.Forms.RadioButton RandomRadio;
            // Generator Results
        private System.Windows.Forms.FlowLayoutPanel ResultFlow;
        private System.Windows.Forms.GroupBox EncounterGenBox;
        private System.Windows.Forms.Label EncounterGenLabel;
        private System.Windows.Forms.GroupBox RoamerGenBox;
        private System.Windows.Forms.Label RoamerGenLabel;
        private System.Windows.Forms.GroupBox EnvironmentGenBox;
        private System.Windows.Forms.Label EnvironmentGenLabel;
        private System.Windows.Forms.TabControl ToolTabs;
        private System.Windows.Forms.TabPage ContinentTab;
        private System.Windows.Forms.TabPage CampaignTab;
        private System.Windows.Forms.TabPage CreationTab;
        private System.Windows.Forms.TabPage CombatTab;
        private System.Windows.Forms.TabPage CompendiumTab;
        private System.Windows.Forms.TabPage EncounterTab;
        private System.Windows.Forms.FlowLayoutPanel ContFilePanel;
        private System.Windows.Forms.Button OpenContButton;
        private System.Windows.Forms.Button SaveContButton;
        private System.Windows.Forms.FlowLayoutPanel SendPanel;
        private System.Windows.Forms.Label SendLabel;
        private System.Windows.Forms.Button ContToEncButton;
        private System.Windows.Forms.Button ContToTrackButton;
        private System.Windows.Forms.Button ContToNotesButton;
        private System.Windows.Forms.Button SaveContAsButton;
    }
}

