/**
 * @file Continental Encoutners.Designer.cs
 * @author: Adair Torres
 * @brief: This file contains code automatically generated by the Visual Studio Designer. The InitializeComponent method should NOT be modified manually.
 * @last modified: 10/28/2022
**/

namespace Continental_Encounters
{
    partial class ContinentForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.BaseMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.viewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ListFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.ZoneGroupBox = new System.Windows.Forms.GroupBox();
            this.NewZoneBox = new System.Windows.Forms.GroupBox();
            this.RemoveZoneBtn = new System.Windows.Forms.Button();
            this.ZoneInput = new System.Windows.Forms.TextBox();
            this.AddZoneBtn = new System.Windows.Forms.Button();
            this.ZoneListBox = new System.Windows.Forms.ListBox();
            this.EncountersGroupBox = new System.Windows.Forms.GroupBox();
            this.NewEncounterBox = new System.Windows.Forms.GroupBox();
            this.RemoveEncounterBtn = new System.Windows.Forms.Button();
            this.EncounterInput = new System.Windows.Forms.TextBox();
            this.AddEncounterBtn = new System.Windows.Forms.Button();
            this.EncounterListBox = new System.Windows.Forms.ListBox();
            this.RoamersGroupBox = new System.Windows.Forms.GroupBox();
            this.NewRoamerBox = new System.Windows.Forms.GroupBox();
            this.RemoveRoamerBtn = new System.Windows.Forms.Button();
            this.RoamerInput = new System.Windows.Forms.TextBox();
            this.AddRoamerBtn = new System.Windows.Forms.Button();
            this.RoamerListBox = new System.Windows.Forms.ListBox();
            this.EnvironmentsGroupBox = new System.Windows.Forms.GroupBox();
            this.NewEnvironmentBox = new System.Windows.Forms.GroupBox();
            this.RemoveEnvironmentBtn = new System.Windows.Forms.Button();
            this.EnvironmentInput = new System.Windows.Forms.TextBox();
            this.AddEnvironmentBtn = new System.Windows.Forms.Button();
            this.EnvironmentListBox = new System.Windows.Forms.ListBox();
            this.NeighborsGroupBox = new System.Windows.Forms.GroupBox();
            this.NewNeighborBox = new System.Windows.Forms.GroupBox();
            this.RemoveNeighborBtn = new System.Windows.Forms.Button();
            this.NeighborInput = new System.Windows.Forms.TextBox();
            this.AddNeighborBtn = new System.Windows.Forms.Button();
            this.NeighborListBox = new System.Windows.Forms.ListBox();
            this.ContinentMain = new System.Windows.Forms.FlowLayoutPanel();
            this.GeneratorGroupBox = new System.Windows.Forms.GroupBox();
            this.GeneratorFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.GenerateBtn = new System.Windows.Forms.Button();
            this.OptionsFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.EncounterCheck = new System.Windows.Forms.CheckBox();
            this.RoamerCheck = new System.Windows.Forms.CheckBox();
            this.EnvironmentCheck = new System.Windows.Forms.CheckBox();
            this.AllRadio = new System.Windows.Forms.RadioButton();
            this.RandomRadio = new System.Windows.Forms.RadioButton();
            this.ResultFlow = new System.Windows.Forms.FlowLayoutPanel();
            this.EnvironmentGenBox = new System.Windows.Forms.GroupBox();
            this.EnvironmentGenLabel = new System.Windows.Forms.Label();
            this.RoamerGenBox = new System.Windows.Forms.GroupBox();
            this.RoamerGenLabel = new System.Windows.Forms.Label();
            this.EncounterGenBox = new System.Windows.Forms.GroupBox();
            this.EncounterGenLabel = new System.Windows.Forms.Label();
            this.AddZoneTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveZoneTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddEncounterTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveEncounterTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddRoamerTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveRoamerTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddEnvironmentTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveEnvironmentTip = new System.Windows.Forms.ToolTip(this.components);
            this.AddNeighborTip = new System.Windows.Forms.ToolTip(this.components);
            this.RemoveNeighborTip = new System.Windows.Forms.ToolTip(this.components);
            this.ToolSidebar = new System.Windows.Forms.FlowLayoutPanel();
            this.ContinentIcon = new System.Windows.Forms.PictureBox();
            this.CombatIcon = new System.Windows.Forms.PictureBox();
            this.CharacterIcon = new System.Windows.Forms.PictureBox();
            this.CompediumIcon = new System.Windows.Forms.PictureBox();
            this.CampaignIcon = new System.Windows.Forms.PictureBox();
            this.CreatorIcon = new System.Windows.Forms.PictureBox();
            this.BaseMenuStrip.SuspendLayout();
            this.ListFlow.SuspendLayout();
            this.ZoneGroupBox.SuspendLayout();
            this.NewZoneBox.SuspendLayout();
            this.EncountersGroupBox.SuspendLayout();
            this.NewEncounterBox.SuspendLayout();
            this.RoamersGroupBox.SuspendLayout();
            this.NewRoamerBox.SuspendLayout();
            this.EnvironmentsGroupBox.SuspendLayout();
            this.NewEnvironmentBox.SuspendLayout();
            this.NeighborsGroupBox.SuspendLayout();
            this.NewNeighborBox.SuspendLayout();
            this.ContinentMain.SuspendLayout();
            this.GeneratorGroupBox.SuspendLayout();
            this.GeneratorFlow.SuspendLayout();
            this.OptionsFlow.SuspendLayout();
            this.ResultFlow.SuspendLayout();
            this.EnvironmentGenBox.SuspendLayout();
            this.RoamerGenBox.SuspendLayout();
            this.EncounterGenBox.SuspendLayout();
            this.ToolSidebar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ContinentIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CombatIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CharacterIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CompediumIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CampaignIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatorIcon)).BeginInit();
            this.SuspendLayout();
            // 
            // BaseMenuStrip
            // 
            this.BaseMenuStrip.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.BaseMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.editToolStripMenuItem,
            this.viewToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.BaseMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.BaseMenuStrip.Name = "BaseMenuStrip";
            this.BaseMenuStrip.Size = new System.Drawing.Size(1565, 28);
            this.BaseMenuStrip.TabIndex = 0;
            this.BaseMenuStrip.Text = "BaseMenuStrip";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.openToolStripMenuItem,
            this.saveAsToolStripMenuItem,
            this.saveToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(46, 24);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // editToolStripMenuItem
            // 
            this.editToolStripMenuItem.Name = "editToolStripMenuItem";
            this.editToolStripMenuItem.Size = new System.Drawing.Size(49, 24);
            this.editToolStripMenuItem.Text = "Edit";
            // 
            // viewToolStripMenuItem
            // 
            this.viewToolStripMenuItem.Name = "viewToolStripMenuItem";
            this.viewToolStripMenuItem.Size = new System.Drawing.Size(55, 24);
            this.viewToolStripMenuItem.Text = "View";
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(55, 24);
            this.helpToolStripMenuItem.Text = "Help";
            // 
            // ListFlow
            // 
            this.ListFlow.Controls.Add(this.ZoneGroupBox);
            this.ListFlow.Controls.Add(this.EncountersGroupBox);
            this.ListFlow.Controls.Add(this.RoamersGroupBox);
            this.ListFlow.Controls.Add(this.EnvironmentsGroupBox);
            this.ListFlow.Controls.Add(this.NeighborsGroupBox);
            this.ListFlow.Location = new System.Drawing.Point(3, 3);
            this.ListFlow.Name = "ListFlow";
            this.ListFlow.Size = new System.Drawing.Size(1050, 315);
            this.ListFlow.TabIndex = 1;
            // 
            // ZoneGroupBox
            // 
            this.ZoneGroupBox.Controls.Add(this.NewZoneBox);
            this.ZoneGroupBox.Controls.Add(this.ZoneListBox);
            this.ZoneGroupBox.Location = new System.Drawing.Point(4, 4);
            this.ZoneGroupBox.Margin = new System.Windows.Forms.Padding(4);
            this.ZoneGroupBox.Name = "ZoneGroupBox";
            this.ZoneGroupBox.Padding = new System.Windows.Forms.Padding(4);
            this.ZoneGroupBox.Size = new System.Drawing.Size(272, 377);
            this.ZoneGroupBox.TabIndex = 0;
            this.ZoneGroupBox.TabStop = false;
            this.ZoneGroupBox.Text = "Zones";
            // 
            // NewZoneBox
            // 
            this.NewZoneBox.Controls.Add(this.RemoveZoneBtn);
            this.NewZoneBox.Controls.Add(this.ZoneInput);
            this.NewZoneBox.Controls.Add(this.AddZoneBtn);
            this.NewZoneBox.Location = new System.Drawing.Point(13, 23);
            this.NewZoneBox.Margin = new System.Windows.Forms.Padding(4);
            this.NewZoneBox.Name = "NewZoneBox";
            this.NewZoneBox.Padding = new System.Windows.Forms.Padding(4);
            this.NewZoneBox.Size = new System.Drawing.Size(243, 55);
            this.NewZoneBox.TabIndex = 2;
            this.NewZoneBox.TabStop = false;
            this.NewZoneBox.Text = "New Zone";
            // 
            // RemoveZoneBtn
            // 
            this.RemoveZoneBtn.Location = new System.Drawing.Point(204, 21);
            this.RemoveZoneBtn.Margin = new System.Windows.Forms.Padding(4);
            this.RemoveZoneBtn.Name = "RemoveZoneBtn";
            this.RemoveZoneBtn.Size = new System.Drawing.Size(31, 28);
            this.RemoveZoneBtn.TabIndex = 2;
            this.RemoveZoneBtn.Text = "-";
            this.RemoveZoneBtn.UseVisualStyleBackColor = true;
            this.RemoveZoneBtn.Click += new System.EventHandler(this.RemoveZoneBtn_Click);
            // 
            // ZoneInput
            // 
            this.ZoneInput.Location = new System.Drawing.Point(8, 23);
            this.ZoneInput.Margin = new System.Windows.Forms.Padding(4);
            this.ZoneInput.Name = "ZoneInput";
            this.ZoneInput.Size = new System.Drawing.Size(160, 22);
            this.ZoneInput.TabIndex = 0;
            // 
            // AddZoneBtn
            // 
            this.AddZoneBtn.Location = new System.Drawing.Point(175, 21);
            this.AddZoneBtn.Margin = new System.Windows.Forms.Padding(4);
            this.AddZoneBtn.Name = "AddZoneBtn";
            this.AddZoneBtn.Size = new System.Drawing.Size(31, 28);
            this.AddZoneBtn.TabIndex = 1;
            this.AddZoneBtn.Text = "+";
            this.AddZoneBtn.UseVisualStyleBackColor = true;
            this.AddZoneBtn.Click += new System.EventHandler(this.AddZoneBtn_Click);
            // 
            // ZoneListBox
            // 
            this.ZoneListBox.FormattingEnabled = true;
            this.ZoneListBox.ItemHeight = 16;
            this.ZoneListBox.Location = new System.Drawing.Point(13, 86);
            this.ZoneListBox.Margin = new System.Windows.Forms.Padding(4);
            this.ZoneListBox.Name = "ZoneListBox";
            this.ZoneListBox.Size = new System.Drawing.Size(241, 276);
            this.ZoneListBox.TabIndex = 1;
            this.ZoneListBox.SelectedIndexChanged += new System.EventHandler(this.ZoneListBox_SelectedIndexChanged);
            // 
            // EncountersGroupBox
            // 
            this.EncountersGroupBox.Controls.Add(this.NewEncounterBox);
            this.EncountersGroupBox.Controls.Add(this.EncounterListBox);
            this.EncountersGroupBox.Location = new System.Drawing.Point(284, 4);
            this.EncountersGroupBox.Margin = new System.Windows.Forms.Padding(4);
            this.EncountersGroupBox.Name = "EncountersGroupBox";
            this.EncountersGroupBox.Padding = new System.Windows.Forms.Padding(4);
            this.EncountersGroupBox.Size = new System.Drawing.Size(272, 377);
            this.EncountersGroupBox.TabIndex = 1;
            this.EncountersGroupBox.TabStop = false;
            this.EncountersGroupBox.Text = "Encounters";
            // 
            // NewEncounterBox
            // 
            this.NewEncounterBox.Controls.Add(this.RemoveEncounterBtn);
            this.NewEncounterBox.Controls.Add(this.EncounterInput);
            this.NewEncounterBox.Controls.Add(this.AddEncounterBtn);
            this.NewEncounterBox.Location = new System.Drawing.Point(13, 23);
            this.NewEncounterBox.Margin = new System.Windows.Forms.Padding(4);
            this.NewEncounterBox.Name = "NewEncounterBox";
            this.NewEncounterBox.Padding = new System.Windows.Forms.Padding(4);
            this.NewEncounterBox.Size = new System.Drawing.Size(243, 55);
            this.NewEncounterBox.TabIndex = 2;
            this.NewEncounterBox.TabStop = false;
            this.NewEncounterBox.Text = "New Encounter";
            // 
            // RemoveEncounterBtn
            // 
            this.RemoveEncounterBtn.Location = new System.Drawing.Point(204, 21);
            this.RemoveEncounterBtn.Margin = new System.Windows.Forms.Padding(4);
            this.RemoveEncounterBtn.Name = "RemoveEncounterBtn";
            this.RemoveEncounterBtn.Size = new System.Drawing.Size(31, 28);
            this.RemoveEncounterBtn.TabIndex = 2;
            this.RemoveEncounterBtn.Text = "-";
            this.RemoveEncounterBtn.UseVisualStyleBackColor = true;
            this.RemoveEncounterBtn.Click += new System.EventHandler(this.RemoveEncounterBtn_Click);
            // 
            // EncounterInput
            // 
            this.EncounterInput.Location = new System.Drawing.Point(8, 23);
            this.EncounterInput.Margin = new System.Windows.Forms.Padding(4);
            this.EncounterInput.Name = "EncounterInput";
            this.EncounterInput.Size = new System.Drawing.Size(160, 22);
            this.EncounterInput.TabIndex = 0;
            // 
            // AddEncounterBtn
            // 
            this.AddEncounterBtn.Location = new System.Drawing.Point(175, 21);
            this.AddEncounterBtn.Margin = new System.Windows.Forms.Padding(4);
            this.AddEncounterBtn.Name = "AddEncounterBtn";
            this.AddEncounterBtn.Size = new System.Drawing.Size(31, 28);
            this.AddEncounterBtn.TabIndex = 1;
            this.AddEncounterBtn.Text = "+";
            this.AddEncounterBtn.UseVisualStyleBackColor = true;
            this.AddEncounterBtn.Click += new System.EventHandler(this.AddEncounterBtn_Click);
            // 
            // EncounterListBox
            // 
            this.EncounterListBox.FormattingEnabled = true;
            this.EncounterListBox.ItemHeight = 16;
            this.EncounterListBox.Location = new System.Drawing.Point(13, 86);
            this.EncounterListBox.Margin = new System.Windows.Forms.Padding(4);
            this.EncounterListBox.Name = "EncounterListBox";
            this.EncounterListBox.Size = new System.Drawing.Size(241, 276);
            this.EncounterListBox.TabIndex = 1;
            this.EncounterListBox.SelectedIndexChanged += new System.EventHandler(this.EncounterListBox_SelectedIndexChanged);
            // 
            // RoamersGroupBox
            // 
            this.RoamersGroupBox.Controls.Add(this.NewRoamerBox);
            this.RoamersGroupBox.Controls.Add(this.RoamerListBox);
            this.RoamersGroupBox.Location = new System.Drawing.Point(564, 4);
            this.RoamersGroupBox.Margin = new System.Windows.Forms.Padding(4);
            this.RoamersGroupBox.Name = "RoamersGroupBox";
            this.RoamersGroupBox.Padding = new System.Windows.Forms.Padding(4);
            this.RoamersGroupBox.Size = new System.Drawing.Size(272, 377);
            this.RoamersGroupBox.TabIndex = 2;
            this.RoamersGroupBox.TabStop = false;
            this.RoamersGroupBox.Text = "Roamers";
            // 
            // NewRoamerBox
            // 
            this.NewRoamerBox.Controls.Add(this.RemoveRoamerBtn);
            this.NewRoamerBox.Controls.Add(this.RoamerInput);
            this.NewRoamerBox.Controls.Add(this.AddRoamerBtn);
            this.NewRoamerBox.Location = new System.Drawing.Point(13, 23);
            this.NewRoamerBox.Margin = new System.Windows.Forms.Padding(4);
            this.NewRoamerBox.Name = "NewRoamerBox";
            this.NewRoamerBox.Padding = new System.Windows.Forms.Padding(4);
            this.NewRoamerBox.Size = new System.Drawing.Size(243, 55);
            this.NewRoamerBox.TabIndex = 2;
            this.NewRoamerBox.TabStop = false;
            this.NewRoamerBox.Text = "New Roamer";
            // 
            // RemoveRoamerBtn
            // 
            this.RemoveRoamerBtn.Location = new System.Drawing.Point(204, 21);
            this.RemoveRoamerBtn.Margin = new System.Windows.Forms.Padding(4);
            this.RemoveRoamerBtn.Name = "RemoveRoamerBtn";
            this.RemoveRoamerBtn.Size = new System.Drawing.Size(31, 28);
            this.RemoveRoamerBtn.TabIndex = 2;
            this.RemoveRoamerBtn.Text = "-";
            this.RemoveRoamerBtn.UseVisualStyleBackColor = true;
            this.RemoveRoamerBtn.Click += new System.EventHandler(this.RemoveRoamerBtn_Click);
            // 
            // RoamerInput
            // 
            this.RoamerInput.Location = new System.Drawing.Point(8, 23);
            this.RoamerInput.Margin = new System.Windows.Forms.Padding(4);
            this.RoamerInput.Name = "RoamerInput";
            this.RoamerInput.Size = new System.Drawing.Size(160, 22);
            this.RoamerInput.TabIndex = 0;
            // 
            // AddRoamerBtn
            // 
            this.AddRoamerBtn.Location = new System.Drawing.Point(175, 21);
            this.AddRoamerBtn.Margin = new System.Windows.Forms.Padding(4);
            this.AddRoamerBtn.Name = "AddRoamerBtn";
            this.AddRoamerBtn.Size = new System.Drawing.Size(31, 28);
            this.AddRoamerBtn.TabIndex = 1;
            this.AddRoamerBtn.Text = "+";
            this.AddRoamerBtn.UseVisualStyleBackColor = true;
            this.AddRoamerBtn.Click += new System.EventHandler(this.AddRoamerBtn_Click);
            // 
            // RoamerListBox
            // 
            this.RoamerListBox.FormattingEnabled = true;
            this.RoamerListBox.ItemHeight = 16;
            this.RoamerListBox.Location = new System.Drawing.Point(13, 86);
            this.RoamerListBox.Margin = new System.Windows.Forms.Padding(4);
            this.RoamerListBox.Name = "RoamerListBox";
            this.RoamerListBox.Size = new System.Drawing.Size(241, 276);
            this.RoamerListBox.TabIndex = 1;
            this.RoamerListBox.SelectedIndexChanged += new System.EventHandler(this.RoamerListBox_SelectedIndexChanged);
            // 
            // EnvironmentsGroupBox
            // 
            this.EnvironmentsGroupBox.Controls.Add(this.NewEnvironmentBox);
            this.EnvironmentsGroupBox.Controls.Add(this.EnvironmentListBox);
            this.EnvironmentsGroupBox.Location = new System.Drawing.Point(844, 4);
            this.EnvironmentsGroupBox.Margin = new System.Windows.Forms.Padding(4);
            this.EnvironmentsGroupBox.Name = "EnvironmentsGroupBox";
            this.EnvironmentsGroupBox.Padding = new System.Windows.Forms.Padding(4);
            this.EnvironmentsGroupBox.Size = new System.Drawing.Size(272, 377);
            this.EnvironmentsGroupBox.TabIndex = 3;
            this.EnvironmentsGroupBox.TabStop = false;
            this.EnvironmentsGroupBox.Text = "Environments";
            // 
            // NewEnvironmentBox
            // 
            this.NewEnvironmentBox.Controls.Add(this.RemoveEnvironmentBtn);
            this.NewEnvironmentBox.Controls.Add(this.EnvironmentInput);
            this.NewEnvironmentBox.Controls.Add(this.AddEnvironmentBtn);
            this.NewEnvironmentBox.Location = new System.Drawing.Point(13, 23);
            this.NewEnvironmentBox.Margin = new System.Windows.Forms.Padding(4);
            this.NewEnvironmentBox.Name = "NewEnvironmentBox";
            this.NewEnvironmentBox.Padding = new System.Windows.Forms.Padding(4);
            this.NewEnvironmentBox.Size = new System.Drawing.Size(243, 55);
            this.NewEnvironmentBox.TabIndex = 2;
            this.NewEnvironmentBox.TabStop = false;
            this.NewEnvironmentBox.Text = "New Environment";
            // 
            // RemoveEnvironmentBtn
            // 
            this.RemoveEnvironmentBtn.Location = new System.Drawing.Point(204, 21);
            this.RemoveEnvironmentBtn.Margin = new System.Windows.Forms.Padding(4);
            this.RemoveEnvironmentBtn.Name = "RemoveEnvironmentBtn";
            this.RemoveEnvironmentBtn.Size = new System.Drawing.Size(31, 28);
            this.RemoveEnvironmentBtn.TabIndex = 2;
            this.RemoveEnvironmentBtn.Text = "-";
            this.RemoveEnvironmentBtn.UseVisualStyleBackColor = true;
            this.RemoveEnvironmentBtn.Click += new System.EventHandler(this.RemoveEnvironmentBtn_Click);
            // 
            // EnvironmentInput
            // 
            this.EnvironmentInput.Location = new System.Drawing.Point(8, 23);
            this.EnvironmentInput.Margin = new System.Windows.Forms.Padding(4);
            this.EnvironmentInput.Name = "EnvironmentInput";
            this.EnvironmentInput.Size = new System.Drawing.Size(160, 22);
            this.EnvironmentInput.TabIndex = 0;
            // 
            // AddEnvironmentBtn
            // 
            this.AddEnvironmentBtn.Location = new System.Drawing.Point(175, 21);
            this.AddEnvironmentBtn.Margin = new System.Windows.Forms.Padding(4);
            this.AddEnvironmentBtn.Name = "AddEnvironmentBtn";
            this.AddEnvironmentBtn.Size = new System.Drawing.Size(31, 28);
            this.AddEnvironmentBtn.TabIndex = 1;
            this.AddEnvironmentBtn.Text = "+";
            this.AddEnvironmentBtn.UseVisualStyleBackColor = true;
            this.AddEnvironmentBtn.Click += new System.EventHandler(this.AddEnvironmentBtn_Click);
            // 
            // EnvironmentListBox
            // 
            this.EnvironmentListBox.FormattingEnabled = true;
            this.EnvironmentListBox.ItemHeight = 16;
            this.EnvironmentListBox.Location = new System.Drawing.Point(13, 86);
            this.EnvironmentListBox.Margin = new System.Windows.Forms.Padding(4);
            this.EnvironmentListBox.Name = "EnvironmentListBox";
            this.EnvironmentListBox.Size = new System.Drawing.Size(241, 276);
            this.EnvironmentListBox.TabIndex = 1;
            this.EnvironmentListBox.SelectedIndexChanged += new System.EventHandler(this.EnvironmentListBox_SelectedIndexChanged);
            // 
            // NeighborsGroupBox
            // 
            this.NeighborsGroupBox.Controls.Add(this.NewNeighborBox);
            this.NeighborsGroupBox.Controls.Add(this.NeighborListBox);
            this.NeighborsGroupBox.Location = new System.Drawing.Point(1124, 4);
            this.NeighborsGroupBox.Margin = new System.Windows.Forms.Padding(4);
            this.NeighborsGroupBox.Name = "NeighborsGroupBox";
            this.NeighborsGroupBox.Padding = new System.Windows.Forms.Padding(4);
            this.NeighborsGroupBox.Size = new System.Drawing.Size(272, 377);
            this.NeighborsGroupBox.TabIndex = 4;
            this.NeighborsGroupBox.TabStop = false;
            this.NeighborsGroupBox.Text = "Neighbors";
            // 
            // NewNeighborBox
            // 
            this.NewNeighborBox.Controls.Add(this.RemoveNeighborBtn);
            this.NewNeighborBox.Controls.Add(this.NeighborInput);
            this.NewNeighborBox.Controls.Add(this.AddNeighborBtn);
            this.NewNeighborBox.Location = new System.Drawing.Point(13, 23);
            this.NewNeighborBox.Margin = new System.Windows.Forms.Padding(4);
            this.NewNeighborBox.Name = "NewNeighborBox";
            this.NewNeighborBox.Padding = new System.Windows.Forms.Padding(4);
            this.NewNeighborBox.Size = new System.Drawing.Size(243, 55);
            this.NewNeighborBox.TabIndex = 2;
            this.NewNeighborBox.TabStop = false;
            this.NewNeighborBox.Text = "New Neighbor";
            // 
            // RemoveNeighborBtn
            // 
            this.RemoveNeighborBtn.Location = new System.Drawing.Point(204, 21);
            this.RemoveNeighborBtn.Margin = new System.Windows.Forms.Padding(4);
            this.RemoveNeighborBtn.Name = "RemoveNeighborBtn";
            this.RemoveNeighborBtn.Size = new System.Drawing.Size(31, 28);
            this.RemoveNeighborBtn.TabIndex = 2;
            this.RemoveNeighborBtn.Text = "-";
            this.RemoveNeighborBtn.UseVisualStyleBackColor = true;
            this.RemoveNeighborBtn.Click += new System.EventHandler(this.RemoveNeighborBtn_Click);
            // 
            // NeighborInput
            // 
            this.NeighborInput.Location = new System.Drawing.Point(8, 23);
            this.NeighborInput.Margin = new System.Windows.Forms.Padding(4);
            this.NeighborInput.Name = "NeighborInput";
            this.NeighborInput.Size = new System.Drawing.Size(160, 22);
            this.NeighborInput.TabIndex = 0;
            // 
            // AddNeighborBtn
            // 
            this.AddNeighborBtn.Location = new System.Drawing.Point(175, 21);
            this.AddNeighborBtn.Margin = new System.Windows.Forms.Padding(4);
            this.AddNeighborBtn.Name = "AddNeighborBtn";
            this.AddNeighborBtn.Size = new System.Drawing.Size(31, 28);
            this.AddNeighborBtn.TabIndex = 1;
            this.AddNeighborBtn.Text = "+";
            this.AddNeighborBtn.UseVisualStyleBackColor = true;
            this.AddNeighborBtn.Click += new System.EventHandler(this.AddNeighborBtn_Click);
            // 
            // NeighborListBox
            // 
            this.NeighborListBox.FormattingEnabled = true;
            this.NeighborListBox.ItemHeight = 16;
            this.NeighborListBox.Location = new System.Drawing.Point(13, 86);
            this.NeighborListBox.Margin = new System.Windows.Forms.Padding(4);
            this.NeighborListBox.Name = "NeighborListBox";
            this.NeighborListBox.Size = new System.Drawing.Size(241, 276);
            this.NeighborListBox.TabIndex = 1;
            this.NeighborListBox.SelectedIndexChanged += new System.EventHandler(this.NeighborListBox_SelectedIndexChanged);
            // 
            // ContinentMain
            // 
            this.ContinentMain.Controls.Add(this.ListFlow);
            this.ContinentMain.Controls.Add(this.GeneratorGroupBox);
            this.ContinentMain.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.ContinentMain.Location = new System.Drawing.Point(118, 30);
            this.ContinentMain.Name = "ContinentMain";
            this.ContinentMain.Size = new System.Drawing.Size(1056, 528);
            this.ContinentMain.TabIndex = 2;
            // 
            // GeneratorGroupBox
            // 
            this.GeneratorGroupBox.Controls.Add(this.GeneratorFlow);
            this.GeneratorGroupBox.Location = new System.Drawing.Point(3, 324);
            this.GeneratorGroupBox.Name = "GeneratorGroupBox";
            this.GeneratorGroupBox.Size = new System.Drawing.Size(1050, 195);
            this.GeneratorGroupBox.TabIndex = 2;
            this.GeneratorGroupBox.TabStop = false;
            this.GeneratorGroupBox.Text = "Generator";
            // 
            // GeneratorFlow
            // 
            this.GeneratorFlow.Controls.Add(this.GenerateBtn);
            this.GeneratorFlow.Controls.Add(this.OptionsFlow);
            this.GeneratorFlow.Controls.Add(this.ResultFlow);
            this.GeneratorFlow.Location = new System.Drawing.Point(6, 11);
            this.GeneratorFlow.Name = "GeneratorFlow";
            this.GeneratorFlow.Size = new System.Drawing.Size(1038, 178);
            this.GeneratorFlow.TabIndex = 0;
            // 
            // GenerateBtn
            // 
            this.GenerateBtn.Location = new System.Drawing.Point(4, 4);
            this.GenerateBtn.Margin = new System.Windows.Forms.Padding(4);
            this.GenerateBtn.Name = "GenerateBtn";
            this.GenerateBtn.Size = new System.Drawing.Size(240, 204);
            this.GenerateBtn.TabIndex = 0;
            this.GenerateBtn.Text = "Generate Encounter!";
            this.GenerateBtn.UseVisualStyleBackColor = true;
            this.GenerateBtn.Click += new System.EventHandler(this.GenerateBtn_Click);
            // 
            // OptionsFlow
            // 
            this.OptionsFlow.Controls.Add(this.EncounterCheck);
            this.OptionsFlow.Controls.Add(this.RoamerCheck);
            this.OptionsFlow.Controls.Add(this.EnvironmentCheck);
            this.OptionsFlow.Controls.Add(this.AllRadio);
            this.OptionsFlow.Controls.Add(this.RandomRadio);
            this.OptionsFlow.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.OptionsFlow.Location = new System.Drawing.Point(189, 3);
            this.OptionsFlow.Name = "OptionsFlow";
            this.OptionsFlow.Size = new System.Drawing.Size(128, 166);
            this.OptionsFlow.TabIndex = 1;
            // 
            // EncounterCheck
            // 
            this.EncounterCheck.AutoSize = true;
            this.EncounterCheck.Location = new System.Drawing.Point(4, 4);
            this.EncounterCheck.Margin = new System.Windows.Forms.Padding(4);
            this.EncounterCheck.Name = "EncounterCheck";
            this.EncounterCheck.Size = new System.Drawing.Size(135, 20);
            this.EncounterCheck.TabIndex = 0;
            this.EncounterCheck.Text = "Include Encounter";
            this.EncounterCheck.UseVisualStyleBackColor = true;
            // 
            // RoamerCheck
            // 
            this.RoamerCheck.AutoSize = true;
            this.RoamerCheck.Location = new System.Drawing.Point(4, 32);
            this.RoamerCheck.Margin = new System.Windows.Forms.Padding(4);
            this.RoamerCheck.Name = "RoamerCheck";
            this.RoamerCheck.Size = new System.Drawing.Size(124, 20);
            this.RoamerCheck.TabIndex = 1;
            this.RoamerCheck.Text = "Include Roamer";
            this.RoamerCheck.UseVisualStyleBackColor = true;
            // 
            // EnvironmentCheck
            // 
            this.EnvironmentCheck.AutoSize = true;
            this.EnvironmentCheck.Location = new System.Drawing.Point(4, 60);
            this.EnvironmentCheck.Margin = new System.Windows.Forms.Padding(4);
            this.EnvironmentCheck.Name = "EnvironmentCheck";
            this.EnvironmentCheck.Size = new System.Drawing.Size(149, 20);
            this.EnvironmentCheck.TabIndex = 2;
            this.EnvironmentCheck.Text = "Include Environment";
            this.EnvironmentCheck.UseVisualStyleBackColor = true;
            // 
            // AllRadio
            // 
            this.AllRadio.AutoSize = true;
            this.AllRadio.Location = new System.Drawing.Point(4, 88);
            this.AllRadio.Margin = new System.Windows.Forms.Padding(4);
            this.AllRadio.Name = "AllRadio";
            this.AllRadio.Size = new System.Drawing.Size(89, 20);
            this.AllRadio.TabIndex = 4;
            this.AllRadio.TabStop = true;
            this.AllRadio.Text = "Include All";
            this.AllRadio.UseVisualStyleBackColor = true;
            this.AllRadio.CheckedChanged += new System.EventHandler(this.AllRadio_CheckedChanged);
            // 
            // RandomRadio
            // 
            this.RandomRadio.AutoSize = true;
            this.RandomRadio.Location = new System.Drawing.Point(4, 116);
            this.RandomRadio.Margin = new System.Windows.Forms.Padding(4);
            this.RandomRadio.Name = "RandomRadio";
            this.RandomRadio.Size = new System.Drawing.Size(80, 20);
            this.RandomRadio.TabIndex = 5;
            this.RandomRadio.TabStop = true;
            this.RandomRadio.Text = "Random";
            this.RandomRadio.UseVisualStyleBackColor = true;
            this.RandomRadio.CheckedChanged += new System.EventHandler(this.RandomRadio_CheckedChanged);
            // 
            // RandomRadio
            // 
            this.RandomRadio.AutoSize = true;
            this.RandomRadio.Location = new System.Drawing.Point(3, 95);
            this.RandomRadio.Name = "RandomRadio";
            this.RandomRadio.Size = new System.Drawing.Size(65, 17);
            this.RandomRadio.TabIndex = 5;
            this.RandomRadio.TabStop = true;
            this.RandomRadio.Text = "Random";
            this.RandomRadio.UseVisualStyleBackColor = true;
            // 
            // ResultFlow
            // 
            this.ResultFlow.Controls.Add(this.EnvironmentGenBox);
            this.ResultFlow.Controls.Add(this.RoamerGenBox);
            this.ResultFlow.Controls.Add(this.EncounterGenBox);
            this.ResultFlow.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.ResultFlow.Location = new System.Drawing.Point(323, 3);
            this.ResultFlow.Name = "ResultFlow";
            this.ResultFlow.Size = new System.Drawing.Size(712, 166);
            this.ResultFlow.TabIndex = 2;
            // 
            // EnvironmentGenBox
            // 
            this.EnvironmentGenBox.Controls.Add(this.EnvironmentGenLabel);
            this.EnvironmentGenBox.Location = new System.Drawing.Point(678, 4);
            this.EnvironmentGenBox.Margin = new System.Windows.Forms.Padding(4);
            this.EnvironmentGenBox.Name = "EnvironmentGenBox";
            this.EnvironmentGenBox.Padding = new System.Windows.Forms.Padding(4);
            this.EnvironmentGenBox.Size = new System.Drawing.Size(267, 201);
            this.EnvironmentGenBox.TabIndex = 4;
            this.EnvironmentGenBox.TabStop = false;
            this.EnvironmentGenBox.Text = "Environment";
            // 
            // EnvironmentGenLabel
            // 
            this.EnvironmentGenLabel.Location = new System.Drawing.Point(8, 25);
            this.EnvironmentGenLabel.Margin = new System.Windows.Forms.Padding(4);
            this.EnvironmentGenLabel.Name = "EnvironmentGenLabel";
            this.EnvironmentGenLabel.Size = new System.Drawing.Size(249, 169);
            this.EnvironmentGenLabel.TabIndex = 1;
            this.EnvironmentGenLabel.Text = "The generated environment will appear here!";
            // 
            // RoamerGenBox
            // 
            this.RoamerGenBox.Controls.Add(this.RoamerGenLabel);
            this.RoamerGenBox.Location = new System.Drawing.Point(403, 4);
            this.RoamerGenBox.Margin = new System.Windows.Forms.Padding(4);
            this.RoamerGenBox.Name = "RoamerGenBox";
            this.RoamerGenBox.Padding = new System.Windows.Forms.Padding(4);
            this.RoamerGenBox.Size = new System.Drawing.Size(267, 201);
            this.RoamerGenBox.TabIndex = 3;
            this.RoamerGenBox.TabStop = false;
            this.RoamerGenBox.Text = "Roamer";
            // 
            // RoamerGenLabel
            // 
            this.RoamerGenLabel.Location = new System.Drawing.Point(8, 23);
            this.RoamerGenLabel.Margin = new System.Windows.Forms.Padding(4);
            this.RoamerGenLabel.Name = "RoamerGenLabel";
            this.RoamerGenLabel.Size = new System.Drawing.Size(249, 169);
            this.RoamerGenLabel.TabIndex = 1;
            this.RoamerGenLabel.Text = "The generated roamer will appear here!";
            // 
            // EncounterGenBox
            // 
            this.EncounterGenBox.Controls.Add(this.EncounterGenLabel);
            this.EncounterGenBox.Location = new System.Drawing.Point(128, 4);
            this.EncounterGenBox.Margin = new System.Windows.Forms.Padding(4);
            this.EncounterGenBox.Name = "EncounterGenBox";
            this.EncounterGenBox.Padding = new System.Windows.Forms.Padding(4);
            this.EncounterGenBox.Size = new System.Drawing.Size(267, 201);
            this.EncounterGenBox.TabIndex = 2;
            this.EncounterGenBox.TabStop = false;
            this.EncounterGenBox.Text = "Encounter";
            // 
            // EncounterGenLabel
            // 
            this.EncounterGenLabel.Location = new System.Drawing.Point(9, 25);
            this.EncounterGenLabel.Margin = new System.Windows.Forms.Padding(4);
            this.EncounterGenLabel.Name = "EncounterGenLabel";
            this.EncounterGenLabel.Size = new System.Drawing.Size(249, 169);
            this.EncounterGenLabel.TabIndex = 0;
            this.EncounterGenLabel.Text = "The generated encounter will appear here!";
            // 
            // ToolSidebar
            // 
            this.ToolSidebar.Controls.Add(this.ContinentIcon);
            this.ToolSidebar.Controls.Add(this.CombatIcon);
            this.ToolSidebar.Controls.Add(this.CharacterIcon);
            this.ToolSidebar.Controls.Add(this.CompediumIcon);
            this.ToolSidebar.Controls.Add(this.CampaignIcon);
            this.ToolSidebar.Controls.Add(this.CreatorIcon);
            this.ToolSidebar.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.ToolSidebar.Location = new System.Drawing.Point(0, 120);
            this.ToolSidebar.Name = "ToolSidebar";
            this.ToolSidebar.Size = new System.Drawing.Size(56, 337);
            this.ToolSidebar.TabIndex = 3;
            // 
            // ContinentIcon
            // 
            this.ContinentIcon.Location = new System.Drawing.Point(3, 3);
            this.ContinentIcon.Name = "ContinentIcon";
            this.ContinentIcon.Size = new System.Drawing.Size(50, 50);
            this.ContinentIcon.TabIndex = 0;
            this.ContinentIcon.TabStop = false;
            // 
            // CombatIcon
            // 
            this.CombatIcon.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.CombatIcon.Location = new System.Drawing.Point(3, 59);
            this.CombatIcon.Name = "CombatIcon";
            this.CombatIcon.Size = new System.Drawing.Size(50, 50);
            this.CombatIcon.TabIndex = 1;
            this.CombatIcon.TabStop = false;
            // 
            // CharacterIcon
            // 
            this.CharacterIcon.Location = new System.Drawing.Point(3, 115);
            this.CharacterIcon.Name = "CharacterIcon";
            this.CharacterIcon.Size = new System.Drawing.Size(50, 50);
            this.CharacterIcon.TabIndex = 2;
            this.CharacterIcon.TabStop = false;
            // 
            // CompediumIcon
            // 
            this.CompediumIcon.Location = new System.Drawing.Point(3, 171);
            this.CompediumIcon.Name = "CompediumIcon";
            this.CompediumIcon.Size = new System.Drawing.Size(50, 50);
            this.CompediumIcon.TabIndex = 3;
            this.CompediumIcon.TabStop = false;
            // 
            // CampaignIcon
            // 
            this.CampaignIcon.Location = new System.Drawing.Point(3, 227);
            this.CampaignIcon.Name = "CampaignIcon";
            this.CampaignIcon.Size = new System.Drawing.Size(50, 50);
            this.CampaignIcon.TabIndex = 4;
            this.CampaignIcon.TabStop = false;
            // 
            // CreatorIcon
            // 
            this.CreatorIcon.Location = new System.Drawing.Point(3, 283);
            this.CreatorIcon.Name = "CreatorIcon";
            this.CreatorIcon.Size = new System.Drawing.Size(50, 50);
            this.CreatorIcon.TabIndex = 5;
            this.CreatorIcon.TabStop = false;
            // 
            // ContinentForm
            // 
            this.saveAsToolStripMenuItem.Name = "saveAsToolStripMenuItem";
            this.saveAsToolStripMenuItem.Size = new System.Drawing.Size(224, 26);
            this.saveAsToolStripMenuItem.Text = "Save As...";
            // 
            // saveToolStripMenuItem
            // 
            this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
            this.saveToolStripMenuItem.Size = new System.Drawing.Size(224, 26);
            this.saveToolStripMenuItem.Text = "Save";
            // 
            // ContinentForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1174, 561);
            this.Controls.Add(this.ToolSidebar);
            this.Controls.Add(this.ContinentMain);
            this.Controls.Add(this.BaseMenuStrip);
            this.MainMenuStrip = this.BaseMenuStrip;
            this.Name = "ContinentForm";
            this.Text = "Continental Encounters";
            this.BaseMenuStrip.ResumeLayout(false);
            this.BaseMenuStrip.PerformLayout();
            this.ListFlow.ResumeLayout(false);
            this.ZoneGroupBox.ResumeLayout(false);
            this.NewZoneBox.ResumeLayout(false);
            this.NewZoneBox.PerformLayout();
            this.EncountersGroupBox.ResumeLayout(false);
            this.NewEncounterBox.ResumeLayout(false);
            this.NewEncounterBox.PerformLayout();
            this.RoamersGroupBox.ResumeLayout(false);
            this.NewRoamerBox.ResumeLayout(false);
            this.NewRoamerBox.PerformLayout();
            this.EnvironmentsGroupBox.ResumeLayout(false);
            this.NewEnvironmentBox.ResumeLayout(false);
            this.NewEnvironmentBox.PerformLayout();
            this.NeighborsGroupBox.ResumeLayout(false);
            this.NewNeighborBox.ResumeLayout(false);
            this.NewNeighborBox.PerformLayout();
            this.ContinentMain.ResumeLayout(false);
            this.GeneratorGroupBox.ResumeLayout(false);
            this.GeneratorFlow.ResumeLayout(false);
            this.OptionsFlow.ResumeLayout(false);
            this.OptionsFlow.PerformLayout();
            this.ResultFlow.ResumeLayout(false);
            this.EnvironmentGenBox.ResumeLayout(false);
            this.RoamerGenBox.ResumeLayout(false);
            this.EncounterGenBox.ResumeLayout(false);
            this.ToolSidebar.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ContinentIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CombatIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CharacterIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CompediumIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CampaignIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatorIcon)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        // Menubar
        private System.Windows.Forms.MenuStrip BaseMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem viewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;

        // Tool Sidebar
        private System.Windows.Forms.FlowLayoutPanel ToolSidebar;
        private System.Windows.Forms.PictureBox ContinentIcon;
        private System.Windows.Forms.PictureBox CombatIcon;
        private System.Windows.Forms.PictureBox CharacterIcon;
        private System.Windows.Forms.PictureBox CompediumIcon;
        private System.Windows.Forms.PictureBox CampaignIcon;
        private System.Windows.Forms.PictureBox CreatorIcon;

        // Continent Container
        private System.Windows.Forms.FlowLayoutPanel ContinentMain;

            // Lists Container
        private System.Windows.Forms.FlowLayoutPanel ListFlow;

            // Zone Group
        private System.Windows.Forms.GroupBox ZoneGroupBox;
                // Zone Input
        private System.Windows.Forms.GroupBox NewZoneBox;
        private System.Windows.Forms.TextBox ZoneInput;
        private System.Windows.Forms.Button AddZoneBtn;
        private System.Windows.Forms.ToolTip AddZoneTip;
        private System.Windows.Forms.Button RemoveZoneBtn;
        private System.Windows.Forms.ToolTip RemoveZoneTip;
                // Zone List
        private System.Windows.Forms.ListBox ZoneListBox;

            // Encounter Group
        private System.Windows.Forms.GroupBox EncountersGroupBox;
                // Encounter Input
        private System.Windows.Forms.GroupBox NewEncounterBox;
        private System.Windows.Forms.TextBox EncounterInput;
        private System.Windows.Forms.Button AddEncounterBtn;
        private System.Windows.Forms.ToolTip AddEncounterTip;
        private System.Windows.Forms.Button RemoveEncounterBtn;
        private System.Windows.Forms.ToolTip RemoveEncounterTip;
                // Encounter List
        private System.Windows.Forms.ListBox EncounterListBox;

            // Roamer Group
        private System.Windows.Forms.GroupBox RoamersGroupBox;
                // Roamer Input
        private System.Windows.Forms.GroupBox NewRoamerBox;
        private System.Windows.Forms.TextBox RoamerInput;
        private System.Windows.Forms.Button AddRoamerBtn;
        private System.Windows.Forms.ToolTip AddRoamerTip;
        private System.Windows.Forms.Button RemoveRoamerBtn;
        private System.Windows.Forms.ToolTip RemoveRoamerTip;
                // Roamer List
        private System.Windows.Forms.ListBox RoamerListBox;

            // Environment Group
        private System.Windows.Forms.GroupBox EnvironmentsGroupBox;
                // Environment Input
        private System.Windows.Forms.GroupBox NewEnvironmentBox;
        private System.Windows.Forms.TextBox EnvironmentInput;
        private System.Windows.Forms.Button AddEnvironmentBtn;
        private System.Windows.Forms.ToolTip AddEnvironmentTip;
        private System.Windows.Forms.Button RemoveEnvironmentBtn;
        private System.Windows.Forms.ToolTip RemoveEnvironmentTip;
                // Environment List
        private System.Windows.Forms.ListBox EnvironmentListBox;

            // Neighbor Group
        private System.Windows.Forms.GroupBox NeighborsGroupBox;
                // Neighbor Input
        private System.Windows.Forms.GroupBox NewNeighborBox;
        private System.Windows.Forms.TextBox NeighborInput;
        private System.Windows.Forms.Button AddNeighborBtn;
        private System.Windows.Forms.ToolTip AddNeighborTip;
        private System.Windows.Forms.Button RemoveNeighborBtn;
        private System.Windows.Forms.ToolTip RemoveNeighborTip;
                // Neighbor List
        private System.Windows.Forms.ListBox NeighborListBox;

        // Generator Container
        private System.Windows.Forms.GroupBox GeneratorGroupBox;
        private System.Windows.Forms.FlowLayoutPanel GeneratorFlow;
            // Generate Button
        private System.Windows.Forms.Button GenerateBtn;
            // Generator Options
        private System.Windows.Forms.FlowLayoutPanel OptionsFlow;
        private System.Windows.Forms.CheckBox EncounterCheck;
        private System.Windows.Forms.CheckBox RoamerCheck;
        private System.Windows.Forms.CheckBox EnvironmentCheck;
        private System.Windows.Forms.RadioButton AllRadio;
        private System.Windows.Forms.RadioButton RandomRadio;
            // Generator Results
        private System.Windows.Forms.FlowLayoutPanel ResultFlow;
        private System.Windows.Forms.GroupBox EncounterGenBox;
        private System.Windows.Forms.Label EncounterGenLabel;
        private System.Windows.Forms.GroupBox RoamerGenBox;
        private System.Windows.Forms.Label RoamerGenLabel;
        private System.Windows.Forms.GroupBox EnvironmentGenBox;
        private System.Windows.Forms.Label EnvironmentGenLabel;
    }
}

